[workspace]
members = [
    "apps/rusagent",
    "apps/ruscp",
    "apps/rusftp",
    "apps/rusplink",
    "apps/rustty",
    "apps/rusttygen",
    "crates/rustty-config",
    "crates/rustty-core",
    "crates/rustty-transport",
    "crates/rustty-ui",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/chardonnay/rustty"
rust-version = "1.85"
authors = ["Daniel Mengel <daniel.mengel@gmail.com>"]

[workspace.dependencies]
crossterm = "0.29.0"
rustty-config = { path = "crates/rustty-config", version = "0.1.0" }
rustty-core = { path = "crates/rustty-core", version = "0.1.0" }
rustty-transport = { path = "crates/rustty-transport", version = "0.1.0" }
rustty-ui = { path = "crates/rustty-ui", version = "0.1.0" }
russh = { version = "0.58.0", default-features = false, features = ["ring", "rsa"] }
serde = { version = "1.0.219", features = ["derive"] }
ssh-key = { version = "=0.6.16", package = "internal-russh-forked-ssh-key", features = ["ed25519", "p256", "p384", "p521", "rsa", "hazmat-allow-insecure-rsa-keys"] }
tokio = { version = "1.0", features = ["io-std", "io-util", "net", "rt", "signal", "sync", "time"] }
toml = "0.8.20"

[workspace.lints.rust]
unsafe_code = "forbid"
