[package]
name = "rusagent"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "RusTTY authentication-agent bootstrap binary."
publish = false

[lints]
workspace = true

[dependencies]
rustty-core.workspace = true
